# Generated by Django 3.2.16 on 2025-12-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('meter_readings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('consumption', models.DecimalField(decimal_places=4, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('issued', 'Выставлен'), ('paid', 'Оплачен'), ('overdue', 'Просрочен')], default='issued', max_length=20)),
                ('issue_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField()),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='contracts.contract')),
                ('meter_reading', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='meter_readings.meterreading')),
            ],
        ),
    ]
