# Generated by Django 3.2.16 on 2025-12-27 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=12)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='contracts.contract')),
            ],
            options={
                'ordering': ['-reading_date'],
                'unique_together': {('contract', 'reading_date')},
            },
        ),
    ]
